# .rubocop.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

# Lint/Syntax:
#   Exclude:
#     - 'Gemfile.lock'
